// JavaScript Document
function screenWidth()
{
	var bodyWidth=document.body.clientWidth;
	/*if(bodyWidth>=1680){
		document.getElementById("bigpicarea").style.width="1680px";
		document.getElementById("sliderimg1").style.width="1680px";
		document.getElementById("sliderimg2").style.width="1680px";
		document.getElementById("sliderimg3").style.width="1680px";
		document.getElementById("imgone").style.width="1680px";
		document.getElementById("imgtwo").style.width="1680px";
		document.getElementById("imgthree").style.width="1680px";
		document.getElementById("imgfour").style.width="1680px";
		document.getElementById("imgfive").style.width="1680px";
		document.getElementById("imgsix").style.width="1680px";
		document.getElementById("imgseven").style.width="1680px";
		document.getElementById("imgeight").style.width="1680px";
		document.getElementById("imgnine").style.width="1680px";
		document.getElementById("thumbs1").style.width="360px";
		document.getElementById("thumbs2").style.width="360px";
		document.getElementById("thumbs3").style.width="360px";
		document.getElementById("smallpicarea").style.left="380px";
		document.getElementById("smallpicarea").style.width="1300px";
		}*/
	if(bodyWidth>1170){
		document.getElementById("bigpicarea").style.width=bodyWidth+"px";
		document.getElementById("sliderimg1").style.width=bodyWidth+"px";
		document.getElementById("sliderimg2").style.width=bodyWidth+"px";
		document.getElementById("sliderimg3").style.width=bodyWidth+"px";
		document.getElementById("imgone").style.width=bodyWidth+"px";
		document.getElementById("imgtwo").style.width=bodyWidth+"px";
		document.getElementById("imgthree").style.width=bodyWidth+"px";
		document.getElementById("imgfour").style.width=bodyWidth+"px";
		document.getElementById("imgfive").style.width=bodyWidth+"px";
		document.getElementById("imgsix").style.width=bodyWidth+"px";
		document.getElementById("imgseven").style.width=bodyWidth+"px";
		document.getElementById("imgeight").style.width=bodyWidth+"px";
		document.getElementById("imgnine").style.width=bodyWidth+"px";
		document.getElementById("thumbs1").style.width=360*bodyWidth/1680+"px";
		document.getElementById("thumbs2").style.width=360*bodyWidth/1680+"px";
		document.getElementById("thumbs3").style.width=360*bodyWidth/1680+"px";
		document.getElementById("smallpicarea").style.left=380*bodyWidth/1680+"px";
		document.getElementById("nav").style.height=bodyWidth*5/8+"px";
		document.getElementById("smallpicarea").style.width=bodyWidth-380*bodyWidth/1680+"px";
		}
	if(bodyWidth<=1170){
		document.getElementById("bigpicarea").style.width="1170px";
		document.getElementById("sliderimg1").style.width="1170px";
		document.getElementById("sliderimg2").style.width="1170px";
		document.getElementById("sliderimg3").style.width="1170px";
		document.getElementById("imgone").style.width="1170px";
		document.getElementById("imgtwo").style.width="1170px";
		document.getElementById("imgthree").style.width="1170px";
		document.getElementById("imgfour").style.width="1170px";
		document.getElementById("imgfive").style.width="1170px";
		document.getElementById("imgsix").style.width="1170px";
		document.getElementById("imgseven").style.width="1170px";
		document.getElementById("imgeight").style.width="1170px";
		document.getElementById("imgnine").style.width="1170px";
		document.getElementById("thumbs1").style.width="227px";
		document.getElementById("thumbs2").style.width="227px";
		document.getElementById("thumbs3").style.width="227px";
		document.getElementById("smallpicarea").style.left="301px";
		document.getElementById("nav").style.height="600px";
		document.getElementById("smallpicarea").style.width="690px";
		}
}
window.onresize=function screenWidth()
{
	var bodyWidth=document.body.clientWidth;
	/*if(bodyWidth>=1680){
		document.getElementById("bigpicarea").style.width="1680px";
		document.getElementById("sliderimg1").style.width="1680px";
		document.getElementById("sliderimg2").style.width="1680px";
		document.getElementById("sliderimg3").style.width="1680px";
		document.getElementById("imgone").style.width="1680px";
		document.getElementById("imgtwo").style.width="1680px";
		document.getElementById("imgthree").style.width="1680px";
		document.getElementById("imgfour").style.width="1680px";
		document.getElementById("imgfive").style.width="1680px";
		document.getElementById("imgsix").style.width="1680px";
		document.getElementById("imgseven").style.width="1680px";
		document.getElementById("imgeight").style.width="1680px";
		document.getElementById("imgnine").style.width="1680px";
		document.getElementById("thumbs1").style.width="360px";
		document.getElementById("thumbs2").style.width="360px";
		document.getElementById("thumbs3").style.width="360px";
		document.getElementById("smallpicarea").style.left="380px";
		document.getElementById("smallpicarea").style.width="1300px";
		}*/
	if(bodyWidth>1170){
		document.getElementById("bigpicarea").style.width=bodyWidth+"px";
		document.getElementById("sliderimg1").style.width=bodyWidth+"px";
		document.getElementById("sliderimg2").style.width=bodyWidth+"px";
		document.getElementById("sliderimg3").style.width=bodyWidth+"px";
		document.getElementById("imgone").style.width=bodyWidth+"px";
		document.getElementById("imgtwo").style.width=bodyWidth+"px";
		document.getElementById("imgthree").style.width=bodyWidth+"px";
		document.getElementById("imgfour").style.width=bodyWidth+"px";
		document.getElementById("imgfive").style.width=bodyWidth+"px";
		document.getElementById("imgsix").style.width=bodyWidth+"px";
		document.getElementById("imgseven").style.width=bodyWidth+"px";
		document.getElementById("imgeight").style.width=bodyWidth+"px";
		document.getElementById("imgnine").style.width=bodyWidth+"px";
		document.getElementById("thumbs1").style.width=360*bodyWidth/1680+"px";
		document.getElementById("thumbs2").style.width=360*bodyWidth/1680+"px";
		document.getElementById("thumbs3").style.width=360*bodyWidth/1680+"px";
		document.getElementById("smallpicarea").style.left=380*bodyWidth/1680+"px";
		document.getElementById("nav").style.height=bodyWidth*5/8+"px";
		document.getElementById("smallpicarea").style.width=bodyWidth-380*bodyWidth/1680+"px";
		}
	if(bodyWidth<=1170){
		document.getElementById("bigpicarea").style.width="1170px";
		document.getElementById("sliderimg1").style.width="1170px";
		document.getElementById("sliderimg2").style.width="1170px";
		document.getElementById("sliderimg3").style.width="1170px";
		document.getElementById("imgone").style.width="1170px";
		document.getElementById("imgtwo").style.width="1170px";
		document.getElementById("imgthree").style.width="1170px";
		document.getElementById("imgfour").style.width="1170px";
		document.getElementById("imgfive").style.width="1170px";
		document.getElementById("imgsix").style.width="1170px";
		document.getElementById("imgseven").style.width="1170px";
		document.getElementById("imgeight").style.width="1170px";
		document.getElementById("imgnine").style.width="1170px";
		document.getElementById("thumbs1").style.width="227px";
		document.getElementById("thumbs2").style.width="227px";
		document.getElementById("thumbs3").style.width="227px";
		document.getElementById("smallpicarea").style.left="301px";
		document.getElementById("nav").style.height="600px";
		document.getElementById("smallpicarea").style.width="690px";
		}
}